[workspace]
members = [
    "spicy-os",
    "riscv-sbi",
    "riscv-sbi-rt",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
riscv-sbi = { path = "riscv-sbi" }
riscv-sbi-rt = { path = "riscv-sbi-rt" }
